### ISSUE TITLE
Can you offer the presentation slides of forkbase in VLDB 2018？

### ISSUE THREAD

**Issue by lulinglingcufe** [ooibc88/forkbase#2]
I am a PhD candidate in Zhejiang University. I appreciate your work and want to give a presentation of this work in the lab seminar. I’d be grateful if you can offer me the slides, thank you!

My email is lulingling *at* email.cufe.edu.cn and lulingling *at*  zju.edu.cn.

**Comment by streamjoin** [comment]
Replied in email.

**Comment by lulinglingcufe** [comment]
Congratulations on your latest work LineageChian that is awarded Best Paper in VLDB 2019.
I appreciate your work and want to give a presentation of this work in the lab seminar. I’d be grateful if you can offer me the slides of **LineageChian**, thank you!

My email is lulingling at zju.edu.cn. Best wishes！

**Comment by lulinglingcufe** [comment]
> 
> 
> Replied in email.

Sorry to bother you again. Congratulations on your latest work LineageChian that is awarded Best Paper in VLDB 2019.
I appreciate this work and want to give a presentation of  **LineageChain** in the lab seminar. Can you please offer me the slides of **LineageChain**. My email is lulingling at zju.edu.cn , Best wishes !

**Comment by streamjoin** [comment]
Thanks for your interest. You may find the slides from the link below: 

https://www.slideshare.net/lqmike/finegrained-secure-and-efficient-data-provenance-on-blockchain-systems

In addition, the code of LineageChain is open source in the following repo: 

https://github.com/ooibc88/FabricSharp
